### ISSUE TITLE
Rebuild Database option fail because of not existing domain

### ISSUE THREAD

**Issue by gregorst3** [SwapBlocks/commander#2]
Hello, Gregorst here.

When using the commander to **_rebuild the database (option 4)_**,
we come in this issue:

```wget: unable to resolve host address ‘snapshots.swapblocks.io’```

**This happens because of line 84 that asks for a not existing domain**
https://github.com/SwapBlocks/commander/blob/master/SWAPBlockscommander.sh#L84

I would suggest changing
from https://snapshots.swapblocks.io/current 
to 
http://sbx-snap.geops.net/latest

**Comment by lancekrogers** [comment]
Thanks just made the change
